### ISSUE TITLE
`play mynotelist` then `rest myduration` doesn't work

### ISSUE THREAD

**Issue by markknol** [ddj231/Handel#4]
If I do this:
```
start
save mynotelist = C3, E3
save myduration = for 1b

save myotherplayable = mynotelist for myduration

play mynotelist
rest myduration

play myotherplayable
finish
```
I think I should hear the same chord twice? But I only hear the chord once.
I only hear `play myotherplayable`, because if you remove that, it doesn't play something.

**Comment by ddj231** [comment]
Hi @markknol, it seems the issue here is that you are attempting to play a notelist without any duration given. 

Changing the relevant line to:

```
play mynotelist for 1b
```
or
```
play mynotelist for myduration
```

Would achieve the desired behavior.

Currently, only Playables can be played in Handel. And Playables are made up of both a notelist and a duration.
