### ISSUE TITLE
Timing question

### ISSUE THREAD

**Issue by markknol** [ddj231/Handel#8]
```
start
	save c = C4, E4, G4
	save dm = D4, F4, A4
	save em = E4, G4, B4
	save f = F4, A4, C5
	save g = G4, B4, D5
	save am = A4, C5, E5
	save bdim = B4, D5, F5

	chunk intro
		play g for 4b
		play c for 4b
		rest for 4b
	endchunk
	
	chunk chorus
		play g for 2b
		play c for 2b
		play dm for 2b
		play f for 2b
		rest for 3b
		play c for 1b
	endchunk
	
	run intro with sound piano, loop for 2
	run chorus with sound piano
finish
```
Hello, me again 😄  I tried the following thing, I defined some basic chords, then make the composition using chunks, but they play at the same time. I think this is intended to allow to play multiple things at the same time.
I also tried to wrap the `run intro` in a `block` (see below), because that would make things run after each other but that doesn't seem to work either.  How to approach this?

```
	block
		run intro with sound piano
	endblock loop for 2

	block
		run chorus with sound piano
	endblock loop for 1
```

**Comment by ddj231** [comment]
Hi @markknol! This is the expected behavior, as of the current version of Handel. Currently, running a chunk is the equivalent (conceptually) of creating a new song track. This is the case from wherever on the call stack the chunk is ran. So your first block loop would create 2 song tracks, and the second would create one song track. And they would all play at the same time.

To achieve what you're looking for in the above program, a ```rest ``` could be used. So:

```
start
	save c = C4, E4, G4
	save dm = D4, F4, A4
	save em = E4, G4, B4
	save f = F4, A4, C5
	save g = G4, B4, D5
	save am = A4, C5, E5
	save bdim = B4, D5, F5

	chunk intro
		play g for 4b
		play c for 4b
		rest for 4b
	endchunk
	
	chunk chorus
                rest for 24b
		play g for 2b
		play c for 2b
		play dm for 2b
		play f for 2b
		rest for 3b
		play c for 1b
	endchunk
	
	run intro with sound piano, loop for 2
	run chorus with sound piano
finish
```

The above would schedule the chorus to start after the second loop of the intro. Basically thinking of chunks as running at the same time gives the intuition of scheduling. 


And if you don't want the rest  duration to be hard coded you can do something along the lines of: 

```
start
	save c = C4, E4, G4
	save dm = D4, F4, A4
	save em = E4, G4, B4
	save f = F4, A4, C5
	save g = G4, B4, D5
	save am = A4, C5, E5
	save bdim = B4, D5, F5

	save wait = for 1b
    save times = 2
    update wait rshift 12 * times - 1

	chunk intro
		play g for 4b
		play c for 4b
		rest for 4b
	endchunk
	
	chunk chorus using abit
                rest abit
		play g for 2b
		play c for 2b
		play dm for 2b
		play f for 2b
		rest for 3b
		play c for 1b
	endchunk
	
	run intro with sound piano, loop for times
	run chorus using wait with sound piano
finish
```

The above sets the amount of times to loop the intro. Knowing the intro is 12 beats, its shifts the wait time by 12 * times (the amount of times to loop). And minus 1 because the original duration is 1b. So it is the equivalent of ```val += 12 * times  - 1 ``` in other languages.

Of course you can take this further.

**Comment by ddj231** [comment]
Hi @markknol. I considered this some more, and I think a ```call``` keyword should be introduced to call chunks synchronously. Will update you when that is live.

So chunks would now be able to be called with ```run``` and ```call```. ```run``` creates a new conceptual song track, and takes parameters (```using``` keyword) and  customizations  to track with the ```with``` keyword. ```call``` calls the chunk in the existing track and takes parameters but does not allow track customizations.

**Comment by ddj231** [comment]
```call``` functionality for running chunks in place (in the current track they are called in) is now live in Handel v0.8.10
